# encoding: utf-8
"""
This is a table of TIMIT-and-ARPABET-to-IPA codes.
"""

timitToIPA = {
    "ng": "ŋ",
    "sh": "ʃ",
    "ch": "tʃ",
    "y": "j",
    "zj": "ʒ",
    "zh": "ʒ",
    "jh": "dʒ",
    "dh": "ð",
    "dx": "ɾ",
    "tq": "ʔ",
    "th": "θ",
    "nx": "n",
    "p": "p",
    "b": "b",
    "m": "m",
    "t": "t",
    "d": "d",
    "n": "n",
    "k": "k",
    "g": "g",
    "s": "s",
    "z": "z",
    "f": "f",
    "v": "v",
    "w": "w",
    "l": "l",
    "r": "r",
    "aa": "ɑ",
    "h": "h",
    "hh": "h",
    "ae": "æ",
    "ah": "ʌ",
    "ah0": "ə",
    "ah1": "ʌ",
    "ao": "ɔ",
    "eh": "ɛ",
    "ih": "ɪ",
    "iy": "i",
    "uh": "ʊ",
    "uw": "u",
    "ay": "ɑɪ",
    "aw": "ɑʊ",
    "ey": "eɪ",
    "ow": "oʊ",
    "oy": "ɔɪ",
    "er": "ɚ",
    "er0": "ɚ",
    "er1": "ɝ",
    "en": "n̩",
    "el": "l̩",
    # Buckeye contains some vowel + consonant sequences
    "ihn": "ɪn",
    "ayn": "ɑɪn",
    "uhn": "ən",
    "ehn": "ɛn",
    "ehm": "ɛm",
    "em": "ɛm",
    "aan": "ɑn",
}
